In [121]:
# Package imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from testCases_v2 import *
import sklearn
import sklearn.datasets
import sklearn.linear_model
from planar_utils import plot_decision_boundary, sigmoid, load_planar_dataset, load_extra_datasets
from sklearn.preprocessing import normalize
%matplotlib inline

np.random.seed(1) # set a seed so that the results are consistent

In [122]:
from sklearn.datasets import load_breast_cancer

In [123]:
data = load_breast_cancer()

In [124]:
# Read the DataFrame, first using the feature data
df = pd.DataFrame(data.data, columns=data.feature_names)
# Add a target column, and fill it with the target data
df['target'] = data.target

In [125]:
#percentage of missing values in each variable
df.isnull().sum()/len(data)*100

mean radius                0.0
mean texture               0.0
mean perimeter             0.0
mean area                  0.0
mean smoothness            0.0
mean compactness           0.0
mean concavity             0.0
mean concave points        0.0
mean symmetry              0.0
mean fractal dimension     0.0
radius error               0.0
texture error              0.0
perimeter error            0.0
area error                 0.0
smoothness error           0.0
compactness error          0.0
concavity error            0.0
concave points error       0.0
symmetry error             0.0
fractal dimension error    0.0
worst radius               0.0
worst texture              0.0
worst perimeter            0.0
worst area                 0.0
worst smoothness           0.0
worst compactness          0.0
worst concavity            0.0
worst concave points       0.0
worst symmetry             0.0
worst fractal dimension    0.0
target                     0.0
dtype: float64

In [126]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [127]:
df.shape

(569, 31)

In [128]:
#data type of variables
df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry      

In [129]:
df['target'].value_counts()

1    357
0    212
Name: target, dtype: int64

In [130]:
df.describe().transpose()

count        mean         std         min  \
mean radius              569.0   14.127292    3.524049    6.981000   
mean texture             569.0   19.289649    4.301036    9.710000   
mean perimeter           569.0   91.969033   24.298981   43.790000   
mean area                569.0  654.889104  351.914129  143.500000   
mean smoothness          569.0    0.096360    0.014064    0.052630   
mean compactness         569.0    0.104341    0.052813    0.019380   
mean concavity           569.0    0.088799    0.079720    0.000000   
mean concave points      569.0    0.048919    0.038803    0.000000   
mean symmetry            569.0    0.181162    0.027414    0.106000   
mean fractal dimension   569.0    0.062798    0.007060    0.049960   
radius error             569.0    0.405172    0.277313    0.111500   
texture error            569.0    1.216853    0.551648    0.360200   
perimeter error          569.0    2.866059    2.021855    0.757000   
area error               569.0   40.337079   45.491006    6.802000   
smoothness error         569.0    0.007041    0.003003    0.001713   
compactness error        569.0    0.025478    0.017908    0.002252   
concavity error          569.0    0.031894    0.030186    0.000000   
concave points error     569.0    0.011796    0.006170    0.000000   
symmetry error           569.0    0.020542    0.008266    0.007882   
fractal dimension error  569.0    0.003795    0.002646    0.000895   
worst radius             569.0   16.269190    4.833242    7.930000   
worst texture            569.0   25.677223    6.146258   12.020000   
worst perimeter          569.0  107.261213   33.602542   50.410000   
worst area               569.0  880.583128  569.356993  185.200000   
worst smoothness         569.0    0.132369    0.022832    0.071170   
worst compactness        569.0    0.254265    0.157336    0.027290   
worst concavity          569.0    0.272188    0.208624    0.000000   
worst concave points     569.0    0.114606    0.065732    0.000000   
worst symmetry           569.0    0.290076    0.061867    0.156500   
worst fractal dimension  569.0    0.083946    0.018061    0.055040   
target                   569.0    0.627417    0.483918    0.000000   

                                25%         50%          75%         max  
mean radius               11.700000   13.370000    15.780000    28.11000  
mean texture              16.170000   18.840000    21.800000    39.28000  
mean perimeter            75.170000   86.240000   104.100000   188.50000  
mean area                420.300000  551.100000   782.700000  2501.00000  
mean smoothness            0.086370    0.095870     0.105300     0.16340  
mean compactness           0.064920    0.092630     0.130400     0.34540  
mean concavity             0.029560    0.061540     0.130700     0.42680  
mean concave points        0.020310    0.033500     0.074000     0.20120  
mean symmetry              0.161900    0.179200     0.195700     0.30400  
mean fractal dimension     0.057700    0.061540     0.066120     0.09744  
radius error               0.232400    0.324200     0.478900     2.87300  
texture error              0.833900    1.108000     1.474000     4.88500  
perimeter error            1.606000    2.287000     3.357000    21.98000  
area error                17.850000   24.530000    45.190000   542.20000  
smoothness error           0.005169    0.006380     0.008146     0.03113  
compactness error          0.013080    0.020450     0.032450     0.13540  
concavity error            0.015090    0.025890     0.042050     0.39600  
concave points error       0.007638    0.010930     0.014710     0.05279  
symmetry error             0.015160    0.018730     0.023480     0.07895  
fractal dimension error    0.002248    0.003187     0.004558     0.02984  
worst radius              13.010000   14.970000    18.790000    36.04000  
worst texture             21.080000   25.410000    29.720000    49.54000  
worst perimeter           84.110000   97.660000   125.40000

In [131]:
normalize = normalize(df)

In [132]:
df_scaled = pd.DataFrame(normalize)
df_scaled.var()

0     1.608613e-05
1     1.226958e-04
2     6.206041e-04
3     2.231692e-03
4     3.424886e-09
5     4.264362e-09
6     5.375150e-09
7     5.408622e-10
8     1.238935e-08
9     1.834541e-09
10    4.321926e-08
11    1.482714e-06
12    2.022068e-06
13    2.363228e-04
14    6.148503e-11
15    8.177024e-10
16    3.081973e-09
17    9.497845e-11
18    3.665304e-10
19    2.831018e-11
20    1.606982e-05
21    2.088535e-04
22    6.313733e-04
23    1.423262e-03
24    6.839613e-09
25    3.071902e-08
26    5.571761e-08
27    2.790645e-09
28    2.880653e-08
29    3.103877e-09
30    6.688050e-07
dtype: float64

In [133]:
#storing the variance and name of variables
variance = df_scaled.var()
columns = df.columns

In [134]:
#saving the names of variables having variance more than a threshold value

variable = [ ]

for i in range(0,len(variance)):
    if variance[i]>=0.0000006: #setting the threshold 
        variable.append(columns[i])

In [135]:
variable

['mean radius',
 'mean texture',
 'mean perimeter',
 'mean area',
 'texture error',
 'perimeter error',
 'area error',
 'worst radius',
 'worst texture',
 'worst perimeter',
 'worst area',
 'target']

In [136]:
# creating a new dataframe using the above variables
new_df = df[variable]
# first five rows of the new data
new_df.head()

mean radius  mean texture  mean perimeter  mean area  texture error  \
0        17.99         10.38          122.80     1001.0         0.9053   
1        20.57         17.77          132.90     1326.0         0.7339   
2        19.69         21.25          130.00     1203.0         0.7869   
3        11.42         20.38           77.58      386.1         1.1560   
4        20.29         14.34          135.10     1297.0         0.7813   

   perimeter error  area error  worst radius  worst texture  worst perimeter  \
0            8.589      153.40         25.38          17.33           184.60   
1            3.398       74.08         24.99          23.41           158.80   
2            4.585       94.03         23.57          25.53           152.50   
3            3.445       27.23         14.91          26.50            98.87   
4            5.438       94.44         22.54          16.67           152.20   

   worst area  target  
0      2019.0       0  
1      1956.0       0  
2      1709.0       0  
3       567.7       0  
4      1575.0       0

In [137]:
#variance of variables in new data
new_df.var()

mean radius            12.418920
mean texture           18.498909
mean perimeter        590.440480
mean area          123843.554318
texture error           0.304316
perimeter error         4.087896
area error           2069.431583
worst radius           23.360224
worst texture          37.776483
worst perimeter      1129.130847
worst area         324167.385102
target                  0.234177
dtype: float64

In [138]:
# shape of new and original data
new_df.shape, df.shape

((569, 12), (569, 31))

In [139]:
# Add a target column, and fill it with the target data
new_df['target'] = data.target

<ipython-input-139-2fcf6d82ba3f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = data.target


# Model with selected variable

In [140]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_df.iloc[:,:-1], new_df.iloc[:,-1], random_state=42)

In [141]:
#Train
model=sklearn.linear_model.LogisticRegression()
model.fit(X_train,y_train)

C:\ESD\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [142]:
# Print test accuracy
LR_predictions = model.predict(X_test)
print ('Accuracy of logistic regression: %d ' % float((np.dot(y_test,LR_predictions) + np.dot(1-y_test,1-LR_predictions))/float(y_test.size)*100) +
       '% ' + "(percentage of correctly labelled datapoints)")

Accuracy of logistic regression: 96 % (percentage of correctly labelled datapoints)


In [143]:
# Print train accuracy
LR_predictions_train = model.predict(X_train)
print ('Accuracy of logistic regression: %d ' % float((np.dot(y_train,LR_predictions_train) + np.dot(1-y_train,1-LR_predictions_train))/float(y_train.size)*100) +
       '% ' + "(percentage of correctly labelled datapoints)")

Accuracy of logistic regression: 95 % (percentage of correctly labelled datapoints)


In [144]:
#TRAIN SET
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print(accuracy_score(y_train,model.predict(X_train)))
print(confusion_matrix(y_train,model.predict(X_train)))

0.9577464788732394
[[148  10]
 [  8 260]]


In [145]:
#TEST SET
print(accuracy_score(y_test,model.predict(X_test)))
print(confusion_matrix(y_test,model.predict(X_test)))

0.965034965034965
[[51  3]
 [ 2 87]]


In [146]:
df.shape

(569, 31)

# Model with all variable

In [147]:
#split
xtr,xte,ytr,yte=train_test_split(df.iloc[:,:-1],df.iloc[:,-1], random_state=42)

In [148]:
#training with all variable
model_all=sklearn.linear_model.LogisticRegression()
model_all.fit(xtr,ytr)

C:\ESD\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [149]:
#Accuracy train
print(accuracy_score(ytr,model_all.predict(xtr)))
print(confusion_matrix(ytr,model_all.predict(xtr)))

0.9413145539906104
[[142  16]
 [  9 259]]


In [150]:
#Accuracy test
print(accuracy_score(yte,model_all.predict(xte)))
print(confusion_matrix(yte,model_all.predict(xte)))

0.965034965034965
[[51  3]
 [ 2 87]]


# Our model complexity is reduced by feature selection,while using all the features i.e. 30 we get test accuracy of 96.5 whereas after dropping 18 variable we have reduced the complexity of the model without affecting the accuracy of the model which remains 96.5